/**:
    ros__parameters:
      video_device: "/dev/v4l/by-id/usb-RYS_HFR_USB2.0_Camera_RYS_HFR_USB2.0_Camera-video-index0"
      framerate: 120.0
      #io_method: "mmap"
      frame_id: "camera"
      pixel_format: "mjpeg2rgb"  # see usb_cam/supported_formats for list of supported formats
      image_width: 1280
      image_height: 720
      camera_name: "CV"
      #camera_info_url: "package://usb_cam/config/camera_info.yaml"
      brightness: 140
      #contrast: -1
      #saturation: -1
      #sharpness: -1
      #gain: -1
      #auto_white_balance: true
      #white_balance: 4000
      #autoexposure: true
      #exposure: 100
      #autofocus: false
      #focus: -1
